music/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.vamshi, name='vamshi'),
    path('music', views.vardhan, name='vardhan'),
      
    path('music/<str:pk>',views.jaswanth, name='jaswanth'),
    path('contact', views.contact, name='contact')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

websitdjango1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music.urls'))
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
    artist=models.CharField(max_length=50)
    Album_Title=models.CharField(max_length=50)
    genre=models.CharField(max_length=10)
    album_logo=models.CharField(max_length=1000)
    casting=models.CharField(max_length=50, default='a')


    def __str__(self):
        return self.Album_Title+'-'+self.artist


    
class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  
    file_type=models.CharField(max_length=10)
    song_title=models.CharField(max_length=250)
    song_play=models.FileField(upload_to='songs')
    def __str__(self):
        return self.song_title+'-'+self.file_type

music/views.py
from django.shortcuts import HttpResponse, render
from .models import *

# Create your views here.
def vamshi(request):
    return render (request, 'music/home.html')



def vardhan(request):
    albums= Album.objects.all()
    

    return render(request,'music/vardhan.html', {'albums':albums} )


def jaswanth(request, pk):
    albums= Album.objects.get(id=pk)

    context = {'albums':albums}
    
    return render (request, 'music/songs.html', context)

def contact(request):
    return render(request, 'music/contact.html')

music/templates/music/home.html
{% extends 'music/base.html' %}
{% block body %}

      
      <div class="jumbotron jumbotron-whats-on bg-white">
        <div class="container">
          <div class="row">
            <div class="col-sm-7 col-sm-push-5 col-md-5 col-md-push-7">
              <h2 class="text-klein-purple">
                What’s on VJ music?
              </h2>
              <div>
                <h3 class="text-klein-purple">
                  Music
                </h3>
                <p>
                  There are millions of songs on VJ MUSIC. Play your favorites, discover new tracks, and build the perfect collection.
                </p>
              </div>
              <div>
                <h3 class="text-klein-purple">
                  Playlists
                </h3>
                <p>
                  You’ll find readymade playlists to match your mood, put together by music fans and experts.
                </p>
              </div>
              <div>
                <h3 class="text-klein-purple">
                  New Releases
                </h3>
                <p>
                  Hear this week’s latest singles and albums, and check out what’s hot in the Top 50.
                </p>
              </div>
            </div>
      
            <div class="col-sm-5 col-sm-pull-7 col-md-6 col-md-pull-5">
              <div class="albums row">
                <img height="219" src="https://timesofindia.indiatimes.com/thumb/msid-66014064,width-1200,height-900,resizemode-4/.jpg"
                     class="album-img col-sm-6"/>
                <img height="219" src="https://m.media-amazon.com/images/M/MV5BYWVlMjVhZWYtNWViNC00ODFkLTk1MmItYjU1MDY5ZDdhMTU3XkEyXkFqcGdeQXVyODIwMDI1NjM@._V1_.jpg"
                     class="album-img col-sm-6"/>
                <img height="219" src="https://www.thenewsminute.com/sites/default/files/styles/slideshow_image_size/public/RRR_Poster.jpeg?itok=mERq7_w0"
                     class="album-img col-sm-6"/>
                <img src="https://www.tollywood.net/wp-content/uploads/2020/01/Ala-Vaikunthapurramuloo-4-days-Telugu-States-Collections.jpg"
                     class="album-img col-sm-6"/>
              </div>
            </div>
          </div>
        </div>
      </div>


      
{% endblock %}


<style>
  .text-klein-purple {
    color: #252525;
    }
    
    .bg-white {
      background-color: #fff;
    }
    
    a.btn-scroll {
      text-decoration: none;
      color: white;
      display: block;
      text-align: center;
    }
    
    a.btn-scroll:hover {
      color: #9bf0e1;
    }
    
    .btn-scroll-text {
      text-transform: uppercase;
      transition: color .3s ease-in-out;
      display: block;
      font-weight: 700;
      letter-spacing: .1em;
      margin-bottom: 20px;
    }
    
    h2 {
      font-size: 50px;
      line-height: 1;
      margin: 0 0 .75em;
      font-weight: 900;
    }
    
    h3 {
      font-size: 40px;
      font-weight: 900;
      line-height: 1.4;
    }
    
    .jumbotron-whats-on {
      text-align: left;
      padding: 180px 0;
    }
    
    .jumbotron p {
      font-weight: 400;
      font-size: 18px;
      margin: 1em 0;
    }
    
    .album-img {
      padding: 0;
    }
    
    body {
      font-family: Helvetica,Arial,sans-serif;
      font-size: 16px;
      line-height: 1.5;
      color: #222326;
    }
    
    .navbar-dark {
      background-color: rgba(0,0,0,.6);
    }
    
    .navbar-dark .navbar-nav>li>a {
      color: #fff;
      padding: 28px 17px;
      font-weight: 700;
      line-height: 24px;
    }
    
    .nav>li>a:focus,
    .nav>li>a:hover {
      background-color: inherit;
      color: #9bf0e1;
    }
    
    .nav .divider {
      background-color: #d9dadc;
      width: 1px;
      height: 16px;
      margin: 32px 17px;
    }
    
    .navbar-logo {
      margin-top: 20px;
      margin-bottom: 20px;
      width: 132px;
      height: 40px;
      background-repeat: no-repeat;
      background-size: 100% 100%;
      font: 0/0 a;
      color: transparent;
      text-shadow: none;
      background-color: transparent;
      border: 0;
      float: left;
      background-image: url('../img/logo.svg');
    }
    
    .bg-main {
      width: 100%;
      height: 100%;
      background: linear-gradient(50deg, #554b91 0, #f539cc 100%);
      position: fixed;
      left: 0;
      top: 0;
      z-index: -1;
    }
    
    .bg-main-img {
      display: block;
      background-image: url('../img/bg-albums.png');
      width: 100%;
      height: 100%;
      background-position: center;
    }
    .text-white {
      color: white;
    }
    
    .jumbotron {
      background: none;
      padding: 100px 0;
      text-align: center;
      margin: 0;
    }
    
    .carousel-control.right, .carousel-control.left {
      background: none;
    }
    
    .btn {
      padding: 17px 48px;
      font-size: 14px;
      line-height: 1;
      border-radius: 500px;
      padding: 18px 48px 16px;
      transition-property: background-color,border-color,color,box-shadow,filter;
      transition-duration: .3s;
      border-width: 0;
      letter-spacing: 2px;
      min-width: 160px;
      text-transform: uppercase;
      white-space: normal;
    }
    
    .jumbotron .btn {
      margin: 20px 10px 30px;
    }
    
    .btn-solid {
      color: #fff;
      background-color: #7c25f8;
    }
    .btn-solid:hover {
      color: #fff;
      background-color: #6207e3;
    }
    
    .btn-lg {
      font-size: 16px;
      line-height: 1;
      border-radius: 500px;
      padding: 21px 56px 19px;
    }
    
    .item h1 {
      font-weight: 900;
    }
    
    .text-signup a {
      color: #fff;
      text-decoration: underline;
    }
    
    #carousel-tour {
      margin-top: 50px;
    }
    @font-face {
      font-family: Circular;
      src: url('circular-medium.woff2');
    }
    
    
    body {
      font-family: Circular,Helvetica,Arial,sans-serif;
      
    }
    
    .footer {
      background-color: black;
      color: white;
      padding: 80px 0 50px;
      text-align: left;
    }
    
    .footer-highlight-aquamarine a {
      color: white;
    }
    
    .footer-highlight-aquamarine a:hover {
      color: #9bf0e1;
    }
    
    .footer-logo a {
      display: block;
      width: 132px;
      height: 40px;
      font: 0/0 a;
      color: transparent;
      border: 0;
      background-image: url('../img/logo.svg');
      background-repeat: no-repeat;
      background-size: 100% 100%;
      margin-bottom: 50px;
    }
    
    .footer .nav-title {
      color: #919496;
      font-size: 12px;
      letter-spacing: .08em;
      margin: 20px 0;
      text-transform: uppercase;
    }
    
    .footer .nav li a {
      padding: 3px 0;
      margin: 0 0 12px;
    }
    
    .col-social {
      margin-top: 20px;
    }
    
    .footer .col-social ul {
      float: right;
    }
    
    .footer .col-social li {
      display: inline-block;
    }
    
    .footer .col-social li a {
      padding: 15px;
      margin-bottom: 12px;
      background-color: #222326;
      border-radius: 30px;
    }
    
    .footer .col-social a:hover {
      background-color: #222326;
    }
    
    .col-social a img {
      width: 24px;
      height: 24px;
    }
    
    .footer .nav-small a {
      color: #919496;
    }
    
    .footer .nav-small li a {
      float: left;
      font-size: 12px;
      font-weight: 400;
      padding: 12px;
      margin: 0;
    }
    
    .row-small {
      margin-top: 100px;
    }
    
    .footer .nav-small li:first-child a {
      padding-left: 0;
    }
    
    .flag-icon-us {
        background-image: url('https://cdn3.iconfinder.com/data/icons/finalflags/256/India-Flag.png');
    }
    
    .flag-icon {
      background-position: 50%;
      background-repeat: no-repeat;
      background-size: contain;
      display: inline-block;
      font-size: 18px;
      height: 1em;
      width: 1.33333333em;
    }
    
    .market, .copyright {
      color: #919496;
      font-size: 12px;
    }
    
    a.market {
      color: #919496;
      text-decoration: none;
    }
    
    p{
        font-size: large;
        font-weight: bold;
        font-family:sans-serif;
        color: rgb(233, 222, 222);
    }
</style>

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block body %}

<img class="img" src="{{ albums.album_logo }}" alt="">
    <h1>movie : {{albums.Album_Title}}</h1>
    <h4 class="">Artist : {{albums.artist}}</h4>
    <h4>Casting : {{albums.casting}}</h4>
    {% for i in albums.song_set.all %}
    <div class="songs-div">
    <p class="p">{{i.song_title}}</p> <br>
    <audio class="audio-bar" controls>
        <source src="{{i.song_play.url}}" type="audio/ogg">
      </audio> <br>
    </div>

    {% endfor %}

<style>
    .songs-div{
        
        display: list-item;
        margin-left: 20%;
        align-items: center;
        list-style: none;
    
    }
    .p{
       
        margin-bottom: 0cm;
        color: rgb(23, 53, 66);
        margin-top: 1cm;
    }

    .audio-bar{
        width: 70%;
        margin-bottom: 1cm;
        box-shadow: black;
    }


    .img{
        margin-left: 15%;
        height: 10cm;
        width: 7cm;
    }

    h1{
        margin-left: 15%;
        font-size:xx-large;
        font-weight:900;
        color: rgb(23, 53, 66);

    }
    h4{
        font-weight:bold;
        margin-left: 15%;
        color: rgb(23, 53, 66);
    }


</style>
{% endblock %}




    

music/templates/music/vardhan.html
{% extends 'music/base.html' %}
{% block body %}
    {% for i in albums %}
    <div class="div">
    <img class="img" src="{{ i.album_logo }}" alt="">
    <a class="btn btn-primary" id="bt" href="{% url 'jaswanth' i.id %}">{{i.Album_Title}}</a> 
    
    </div>
{% endfor %}
   
<style>
    .img{
        
        height: 8cm;
        width: 6cm;
        margin-bottom: 3cm;
        margin-left: 20%;
        
    }


.div{
    display:inline-flexbox;
    justify-content: space-around;
}

#bt{
    margin-left: 2cm;
}
</style>


    
{% endblock %}